site_name: VISU
repo_url: https://github.com/phpgl/visu
site_url: https://visu.phpgl.net
use_directory_urls: false
nav:
  - Home: index.md
plugins:
  - search
  - include_dir_to_nav
  
  # - tags
theme:
  name: material
  custom_dir: docs/overrides
  logo: ./logo_phpglfw_s.png
  font:
    text: Source Sans Pro
  palette:
    scheme: default
    primary: black
  features:
    - navigation.tabs
extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2022 Mario Döring / @see <a target="_blank" href="https://github.com/phpgl/visu/blob/master/LICENSE">LICENSE</a>
extra:
  generator: false
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.extra
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.highlight:
      anchor_linenums: true
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - toc:
      permalink: true
